import { MSWProvider } from '../shared/ui/providers/msw-provider';
import './global.css';

export const metadata = {
  title: 'Welcome to main',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MSWProvider>{children}</MSWProvider>
      </body>
    </html>
  );
}
